services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: potiskarium-php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9001:9000"
      - "9004:9003"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    image: mariadb:12.0.2-ubi10
    container_name: potiskarium-mysql
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=potiskarium
      - MYSQL_USER=potiskarium
      - MYSQL_PASSWORD=potiskarium
    ports:
      - 3381:3306
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql/

  nginx:
    image: nginx:alpine
    container_name: potiskarium-nginx
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    depends_on:
      - app
