services:

  db:
    image: mariadb:12.0.2-ubi10
    container_name: potiskarium-mysql
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=potiskarium
      - MYSQL_USER=potiskarium
      - MYSQL_PASSWORD=potiskarium
    ports:
      - 3381:3306
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql/

  ftp:
    image: delfer/alpine-ftp-server
    container_name: potiskarium-ftp
    volumes:
      - ./src/wordpress:/var/www/html
    environment:
      - USERS=ftp1|ftp1234|/var/www/html
      - ADDRESS=ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"

  nginx:
    image: nginx:alpine
    container_name: potiskarium-nginx
    volumes:
      - ./src/:/var/www/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: potiskarium-php
    volumes:
      - ./src/:/var/www/
      - ./docker/php-my.ini:/usr/local/etc/php/conf.d/php-my.ini
    working_dir: /var/www/wordpress
    entrypoint: >
      sh -c "
        ln -sfn /var/www/comgate-plugin /var/www/wordpress/wp-content/plugins/comgate-plugin &&
        ln -sfn /var/www/potiskarium-construction /var/www/wordpress/wp-content/themes/potiskarium-construction &&
        ln -sfn /var/www/potiskarium-theme /var/www/wordpress/wp-content/themes/potiskarium-theme &&
        php-fpm
      "
    ports:
      - "9001:9000"
      - "9004:9003"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - ftp
